<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_controls</name>
   <tag></tag>
   <elementGuidId>f97f6cb9-ed1a-4a5c-ade5-e4524913d478</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>controls</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressInfo&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-3 col-sm-6 col-xs-12&quot;]/div[@class=&quot;controls&quot;]</value>
   </webElementProperties>
</WebElementEntity>
