<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select ProjectSWE- Chri</name>
   <tag></tag>
   <elementGuidId>9df6c029-ce6e-4bb6-be4f-5e2e0b7b59c5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>project</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProjectSWE- Christ BentonDaniel Hardmankrocks- k ptest comp- Prit Cust test priApple- Check ContractorBusiness Affliate Test- test_1 Test_1LastRetest LiveRetest Again testRetest Pri 12121test testretest test retestPhone number TestERER REERRTest pn PNTest DOL Test DOLTest iiii test iiiiTest- Test Project TestEmp Test Test EMpTest Testretest addn info infoPp ColaradoTest TestDOL DOLPUBG- john doeHoffman Medina LLC- Ira RomeroDhiraj Plumb- dhiraj_cust karkera_custProject WithoutBillingRetest Pri 12121DOL1 CheckDOL without DOL CheckDhiraj Plumb- dhiraj_cust karkera_custretest Projtestnew billing billingAddr test TestMyCompany- firsttest lasttestProject Details BillingInsuranceabc xyztest testmy ProjTestInsBill Ins BillNew Pro projFinalINS BIL Ins BIlTest category TestTest Contact test ContactNew proj KPNew proj KPCategory search TestWithout Business CategoryPhone number test testMontgomery Glenn Trading- Sacha JohnstonPhone number TestTestnew testTest Add test AddTestSubsProj SubsProjTax Cal CaliPad test iPad testTime check Time checkTime check again Time check againEmployee time retest retestaasdasd- Test email Test emailTest test Lst nameadasdas sadasdasTest TestTest project TestRetest retestemail retest retestRetest retestTest Test TestTest Tests- Jeniffer LopesTest Tests- Jeniffer Lopesdasdsd dasdsddasdsd dasdsdTest mobile MobNew lead RetestNew proj com- New proj live TestNew proj com- New proj live TestNew lead RetestNew lead RetestInv test TeestProject company- Proj retestABC XYZ- Proj newEmp company 1- testemp123 retest1Retest open office- John TestTest John#abc-12 Company name- Retest John#abc-12 Company name- Retest John#123Company-name- Leads Retest#Google-Dummy- Abc 'Dmen retest#Google-Dummy- Abc 'Dmen retestAbc company test -123- Mary DoeZycon- Mavrecik D'mac-GoGGle- Mader Testtest- test testAbc Company Test- Test Test1234567789 12354566777123 Josh testTest Customer company #122-1223{}_+>?- John'Test D'mellogreentecrestoration.com- Josh Testtest testRichard Sanchez Co- Richard HouseTest company- Test testasdsa dsadasLancaster and Miles LLC- Kermit ThompsonABC comp- Test P PrinceABN Company- testsedf JoerTest Holding LLCs- Test Doeasdasd- asdasdas sdasdasabcd- slade Wilsonabcd- slade Wilsonsdsad- sadsadsad sdsadsadsadsdsdsad- adsadsads sdsadsaabcd- val boleabcd- val boleabcd- val boleabcd- val bole</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project&quot;)</value>
   </webElementProperties>
</WebElementEntity>
