<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_flex-group</name>
   <tag></tag>
   <elementGuidId>56b9b953-e5a3-4129-a271-59251ee2e1f2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-group</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timesheetForm&quot;)/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;form-group form-group-wrapper-setting&quot;]/label[@class=&quot;flex-group&quot;]</value>
   </webElementProperties>
</WebElementEntity>
